// <auto-generated />
using System;
using DocUploader.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocUploader.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231027052919_DocumentCategories")]
    partial class DocumentCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DocUploader.Shared.AuthModels.ApiUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ClientName")
                        .HasColumnType("longtext");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Last4Digits")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "KRMN8-SHDA3-BGMNP-MP88",
                            AccessFailedCount = 0,
                            ClientName = "Admin",
                            ConcurrencyStamp = "59556a30-ebb2-45a4-aaec-83e11c45d0cd",
                            Email = "admin@ltarsde.com",
                            EmailConfirmed = false,
                            Last4Digits = "1234",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LTARSDE.COM",
                            NormalizedUserName = "ADMIN@LTARSDE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELcelnE2Y2ciAfH0CiIc3VUuFJMMOuftQRLEWrluKpKNrZes3h3oFzIUlv1JoANJTw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5b10def5-303c-481f-abe9-ada041a043fb",
                            TwoFactorEnabled = false,
                            UserName = "admin@ltarsde.com"
                        },
                        new
                        {
                            Id = "SHDRE-COM2T-FF99Z-GM55",
                            AccessFailedCount = 0,
                            ClientName = "Admin",
                            ConcurrencyStamp = "7d934d64-20a6-4b17-be0d-04ce2faf182d",
                            Email = "user@ltarsde.com",
                            EmailConfirmed = false,
                            Last4Digits = "1234",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@LTARSDE.COM",
                            NormalizedUserName = "USER@LTARSDE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGDgiphYiUlIwqbQ5/R3FpIY5bj4/ZGzhefh+/GZ9vh6jzE+IlN92PTLz/XdBZZ3HA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ae915261-f211-4cb2-ab64-d87b1763e556",
                            TwoFactorEnabled = false,
                            UserName = "user@ltarsde.com"
                        });
                });

            modelBuilder.Entity("DocUploader.Shared.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClientIdInternal")
                        .HasColumnType("int");

                    b.Property<string>("ClientName")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Last4Digits")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("DocUploader.Shared.Models.ClientDocumentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DocumentCategoryId");

                    b.ToTable("ClientDocumentCategories");
                });

            modelBuilder.Entity("DocUploader.Shared.Models.ClientsRequest", b =>
                {
                    b.Property<int>("ClientRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("ClientRequestId");

                    b.HasIndex("ClientId");

                    b.HasIndex("RequestId");

                    b.ToTable("ClientsRequests");
                });

            modelBuilder.Entity("DocUploader.Shared.Models.DocumentCategory", b =>
                {
                    b.Property<int>("DocumentCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DocumentCategoryId");

                    b.ToTable("DocumentCategories");
                });

            modelBuilder.Entity("DocUploader.Shared.Models.GenericModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DocumentName")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GenericModels");
                });

            modelBuilder.Entity("DocUploader.Shared.Models.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("RequestIdInternal")
                        .HasColumnType("int");

                    b.Property<string>("RequestName")
                        .HasColumnType("longtext");

                    b.HasKey("RequestId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("DocUploader.Shared.Models.RequestDocuments", b =>
                {
                    b.Property<int>("RequestDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ClientsRequestClientRequestId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentName")
                        .HasColumnType("longtext");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("RequestDocumentId");

                    b.HasIndex("ClientsRequestClientRequestId");

                    b.HasIndex("RequestId");

                    b.ToTable("RequestDocuments");
                });

            modelBuilder.Entity("DocUploader.Shared.Models.TableModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateUploaded")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DocumentName")
                        .HasColumnType("longtext");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TableModels");
                });

            modelBuilder.Entity("DocUploader.Shared.Models.TwoFactorAuth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TwoFactorAuths");
                });

            modelBuilder.Entity("DocUploader.Shared.Models.UploadedDocuments", b =>
                {
                    b.Property<int>("UploadedDocumentsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("ClientRequestId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientsRequestClientRequestId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentPath")
                        .HasColumnType("longtext");

                    b.HasKey("UploadedDocumentsId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientsRequestClientRequestId");

                    b.ToTable("UploadedDocuments");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ACD89-BAF03-ZKR88-99MN",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "3BGTS-ISBNX-89KRK-YYZZ",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "KRMN8-SHDA3-BGMNP-MP88",
                            RoleId = "ACD89-BAF03-ZKR88-99MN"
                        },
                        new
                        {
                            UserId = "SHDRE-COM2T-FF99Z-GM55",
                            RoleId = "3BGTS-ISBNX-89KRK-YYZZ"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DocUploader.Shared.Models.ClientDocumentCategory", b =>
                {
                    b.HasOne("DocUploader.Shared.Models.Client", "Client")
                        .WithMany("ClientDocumentCategories")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocUploader.Shared.Models.DocumentCategory", "DocumentCategory")
                        .WithMany("ClientDocumentCategories")
                        .HasForeignKey("DocumentCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("DocumentCategory");
                });

            modelBuilder.Entity("DocUploader.Shared.Models.ClientsRequest", b =>
                {
                    b.HasOne("DocUploader.Shared.Models.Client", "Client")
                        .WithMany("ClientsRequests")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocUploader.Shared.Models.Request", "Request")
                        .WithMany("ClientsRequests")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("DocUploader.Shared.Models.RequestDocuments", b =>
                {
                    b.HasOne("DocUploader.Shared.Models.ClientsRequest", null)
                        .WithMany("RequestDocuments")
                        .HasForeignKey("ClientsRequestClientRequestId");

                    b.HasOne("DocUploader.Shared.Models.Request", "Request")
                        .WithMany("RequestDocuments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("DocUploader.Shared.Models.UploadedDocuments", b =>
                {
                    b.HasOne("DocUploader.Shared.Models.Client", null)
                        .WithMany("UploadedDocuments")
                        .HasForeignKey("ClientId");

                    b.HasOne("DocUploader.Shared.Models.ClientsRequest", "ClientsRequest")
                        .WithMany("UploadedDocuments")
                        .HasForeignKey("ClientsRequestClientRequestId");

                    b.Navigation("ClientsRequest");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DocUploader.Shared.AuthModels.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DocUploader.Shared.AuthModels.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocUploader.Shared.AuthModels.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DocUploader.Shared.AuthModels.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DocUploader.Shared.Models.Client", b =>
                {
                    b.Navigation("ClientDocumentCategories");

                    b.Navigation("ClientsRequests");

                    b.Navigation("UploadedDocuments");
                });

            modelBuilder.Entity("DocUploader.Shared.Models.ClientsRequest", b =>
                {
                    b.Navigation("RequestDocuments");

                    b.Navigation("UploadedDocuments");
                });

            modelBuilder.Entity("DocUploader.Shared.Models.DocumentCategory", b =>
                {
                    b.Navigation("ClientDocumentCategories");
                });

            modelBuilder.Entity("DocUploader.Shared.Models.Request", b =>
                {
                    b.Navigation("ClientsRequests");

                    b.Navigation("RequestDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
